import { StyleSheet } from "react-native";

export const myStyle = StyleSheet.create({
    bg: {
        height: "100%",
        alignItems: 'center',
        justifyContent: "center",
        width: "100%",
    },
    main_pocket: {
        backgroundColor: "white",
        width: "80%",
        paddingVertical: 30,
        borderRadius: 20,
        alignItems: "center",
        marginVertical: 25,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    pocket: {
        backgroundColor: "white",
        width: "80%",
        height: 50,
        borderRadius: 30,
        borderWidth: 1,
        borderColor: '#000',
        paddingHorizontal: 15,
        flexDirection: "row",
        alignItems: "center",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    add_pocket: {
        backgroundColor: "#38E298",
        width: "80%",
        height: 50,
        borderRadius: 25,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 4,
    },
});
