name: iOS Build and Test with Detox

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install JS dependencies
        run: |
          cd project_soft_eng
          npm install

      - name: Install CocoaPods
        run: |
          cd project_soft_eng/ios
          pod install
          cd ..

      - name: Build iOS App
        run: |
          cd project_soft_eng
          npx detox build --configuration ios.debug

      - name: Run Detox Tests
        run: |
          cd project_soft_eng
          npx detox test --configuration ios.debug --failFast || exit 1

      - name: Upload Detox Logs
        uses: actions/upload-artifact@v3
        with:
          name: Detox Logs
          path: project_soft_eng/detox/test-artifacts
