name: iOS Build and Test with Detox

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'


      # ติดตั้ง dependencies ทั้งหมดของโครงการ
      - name: Install JS dependencies
        run: |
          cd project_soft_eng
          npm install --force

      - name: Install CocoaPods
        run: |
          cd project_soft_eng
          cd ios
          pod install
          cd ..

      # Build ด้วย detox config
      - name: Build iOS App
        run: |
          cd project_soft_eng
          npx detox build --configuration ios.debug

      # รันเทส Detox
      - name: Run Detox Tests
        run: |
          cd project_soft_eng
          npx detox test --configuration ios.debug  

      